database:
  user: "admin"
  password: "password"
  host: "localhost"
  port: 27017
  database: "runithstats"
  collection: "player_stats"
  thread-pool: 4
  connect-timeout-seconds: 3
  read-timeout-seconds: 2