name: RunithStats
version: '1.0-SNAPSHOT'
main: net.runith.runithstats.RunithStatsPlugin
api-version: 1.8
authors: [Runith]
website: https://github.com/RunithMC

description: Track plugin statistics.

commands:
  runithstats:
    description: Comando principal de RunithStats
    usage: /runithstats [set <kills|deaths> <jugador> <valor>]
    permission: runithstats.use

permissions:
  runithstats.use:
    description: Permite usar el comando principal
    default: true
  runithstats.admin:
    description: Permite modificar estadísticas de otros jugadores
    default: op

depend:
  - PlaceholderAPI
softdepend:
  - PvPManager